### ISSUE TITLE
Is this library also working with Google Drive REST API v3?

### ISSUE THREAD

**Issue by Ionna** [google/google-api-java-client#1014]
I have tried to "migrate" to the new version of the API. But as far as I understood from the [documentation](https://developers.google.com/drive/v3/web/quickstart/java#step_3_set_up_the_sample) website the very same library should be used. However, I get several errors with the message "java: cannot find method" because it seems there is no definition for the methods in the library.</p>
Should I stick with v2 or what have I got wrong?</p>
Thank you very much!

**Comment by mattwhisenhunt** [comment]
"We will continue to support both versions so that existing apps using v2 can run without changes (developers don’t have to upgrade). For developers with a v2 app who want to take advantage of the new improvements, we’ve got a handy cheat sheet to help with [migration](https://developers.google.com/drive/v3/web/migration)."

https://developers.googleblog.com/2015/12/a-leaner-and-faster-google-drive-api.html
