### ISSUE TITLE
Storage API sample has misleading commentary in the code

### ISSUE THREAD

**Issue by raggi** [google/google-api-java-client#962]
See https://github.com/google/google-api-java-client-samples/blob/master/storage-cmdline-sample/src/main/java/com/google/api/services/samples/storage/examples/ObjectsUploadExample.java#L60

And https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance#gzip

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to re-open this issue and explain why you believe fixing it is essential for users of this client library.
