### ISSUE TITLE
Using GoogleCredentials from Service account - JSON/p12

### ISSUE THREAD

**Issue by mytwilight** [google/google-api-java-client#993]
Hello, 

I am trying to get GoogleCredentials using JAVA Client library and want to make cloud compute API calls.  
I intend to use Service account for auth.

The service account credentials can be downloaded in 2 formats - JSON (recommended) and p12 format (maintained for backward compatibility).

The APIs now should use these credentials to make API calls.

The documentation says place the JSON in a path pointed by GOOGLE_APPLICATION_CREDENTIALS. But storing JSON format credentials are not safe and secure.

In that case P12 seems to be good option, but does not seem to have a long term existence.
I would like to know what are the drawbacks of using p12 (encrypted PKCS#12) file.

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to re-open this issue and explain why you believe fixing it is essential for users of this client library.
